name: CI
on:
  push:
  workflow_dispatch:
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.OTO_DOCKER_USER }}
          password: ${{ secrets.OTO_DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.base
          push: true
          tags: otomato/nexus3-cli:latest