# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: prepare files
        run: |
          mkdir files
          echo one > files/one
          echo two > files/two
      - name: Publish files
        uses: otomato-gh/nexus3-oss-action@main
        with:
          serverUrl: http://nexus.texel.live
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repositorypath: test-me/1.0.0
          files: ./files/
